// <auto-generated />
namespace TeamSignificance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initmirgation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initmirgation));
        
        string IMigrationMetadata.Id
        {
            get { return "202010101731214_Init mirgation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
